# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_home_widget(object):
    def setupUi(self, home_widget):
        home_widget.setObjectName("home_widget")
        home_widget.resize(710, 593)
        self.ProgressRing = ProgressRing(home_widget)
        self.ProgressRing.setGeometry(QtCore.QRect(500, 80, 100, 100))
        self.ProgressRing.setObjectName("ProgressRing")
        self.AvatarWidget = AvatarWidget(home_widget)
        self.AvatarWidget.setGeometry(QtCore.QRect(30, 80, 96, 96))
        self.AvatarWidget.setObjectName("AvatarWidget")

        self.retranslateUi(home_widget)
        QtCore.QMetaObject.connectSlotsByName(home_widget)

    def retranslateUi(self, home_widget):
        _translate = QtCore.QCoreApplication.translate
        home_widget.setWindowTitle(_translate("home_widget", "Form"))
from qfluentwidgets import AvatarWidget, ProgressRing


